import { AppId } from '../types';

export interface AppMetadata {
  id: AppId;
  name: string;
  title: string;
  icon: string;
  category: 'portfolio' | 'development' | 'productivity' | 'media' | 'system' | 'entertainment';
  description: string;
  defaultSize: { width: number; height: number };
  minimumSize: { width: number; height: number };
  supportedFileTypes?: string[];
  keyboardShortcut?: string;
  permissions?: string[];
  availableModes: ('explorer' | 'recruiter' | 'developer')[];
  isPinnedDefault?: boolean;
}

export const APP_REGISTRY: Record<AppId, AppMetadata> = {
  'browser': {
    id: 'browser',
    name: 'Abhishek Browser',
    title: 'Abhishek Browser',
    icon: 'Globe',
    category: 'development',
    description: 'Modern developer browser with integrated search engine, tab manager, AI summarizer, and bookmarks.',
    defaultSize: { width: 960, height: 640 },
    minimumSize: { width: 480, height: 380 },
    keyboardShortcut: 'Ctrl + B',
    availableModes: ['explorer', 'developer'],
    isPinnedDefault: true,
  },
  'ai': {
    id: 'ai',
    name: 'Abhishek AI Copilot',
    title: 'Abhishek AI — Portfolio & OS Assistant',
    icon: 'Sparkles',
    category: 'development',
    description: 'Intelligent portfolio assistant with RAG knowledge base, safe OS voice commands, and note generation.',
    defaultSize: { width: 780, height: 580 },
    minimumSize: { width: 420, height: 400 },
    permissions: ['microphone'],
    keyboardShortcut: 'Ctrl + Shift + A',
    availableModes: ['explorer', 'recruiter', 'developer'],
    isPinnedDefault: true,
  },
  'terminal': {
    id: 'terminal',
    name: 'Terminal 2.0',
    title: 'PowerShell / Developer Terminal',
    icon: 'Terminal',
    category: 'development',
    description: 'Simulated PowerShell terminal connecting to virtual filesystem, Git, and interactive OS window commands.',
    defaultSize: { width: 780, height: 520 },
    minimumSize: { width: 400, height: 300 },
    keyboardShortcut: 'Ctrl + `',
    availableModes: ['explorer', 'developer'],
    isPinnedDefault: true,
  },
  'git': {
    id: 'git',
    name: 'Abhishek Git Studio',
    title: 'Abhishek Git — Interactive Version Control & Graph',
    icon: 'GitBranch',
    category: 'development',
    description: 'Visual Git graph, branch visualization, commit timeline, staging manager, and diff viewer.',
    defaultSize: { width: 880, height: 580 },
    minimumSize: { width: 500, height: 360 },
    keyboardShortcut: 'Ctrl + G',
    availableModes: ['explorer', 'developer'],
    isPinnedDefault: true,
  },
  'api-tester': {
    id: 'api-tester',
    name: 'Abhishek API Lab',
    title: 'Abhishek API Lab — HTTP & REST Client',
    icon: 'Send',
    category: 'development',
    description: 'Postman-inspired API testing suite with GET/POST/PUT/DELETE, headers, params, and response formatter.',
    defaultSize: { width: 880, height: 580 },
    minimumSize: { width: 480, height: 380 },
    availableModes: ['explorer', 'developer'],
    isPinnedDefault: true,
  },
  'code-editor': {
    id: 'code-editor',
    name: 'Abhishek Code Studio',
    title: 'Abhishek Code — TypeScript IDE',
    icon: 'Code2',
    category: 'development',
    description: 'Full-featured code workstation with syntax highlighting, line numbers, virtual files, and built-in runner.',
    defaultSize: { width: 920, height: 600 },
    minimumSize: { width: 500, height: 360 },
    supportedFileTypes: ['ts', 'tsx', 'js', 'json', 'html', 'css'],
    availableModes: ['explorer', 'developer'],
    isPinnedDefault: true,
  },
  'writer': {
    id: 'writer',
    name: 'Abhishek Writer',
    title: 'Abhishek Writer — Document Processor',
    icon: 'FileText',
    category: 'productivity',
    description: 'Word-inspired rich document editor with real-time formatting, statistics, and VFS autosave.',
    defaultSize: { width: 860, height: 580 },
    minimumSize: { width: 460, height: 360 },
    supportedFileTypes: ['abkdoc', 'txt', 'md'],
    availableModes: ['explorer', 'productivity' as any, 'recruiter'],
    isPinnedDefault: true,
  },
  'sheets': {
    id: 'sheets',
    name: 'Abhishek Sheets',
    title: 'Abhishek Sheets — Spreadsheet Engine',
    icon: 'Table',
    category: 'productivity',
    description: 'Spreadsheet engine with formula processing (=SUM, =AVERAGE, =COUNT), charts, and CSV export.',
    defaultSize: { width: 920, height: 580 },
    minimumSize: { width: 500, height: 360 },
    supportedFileTypes: ['abkxlsx', 'csv'],
    availableModes: ['explorer', 'developer'],
    isPinnedDefault: true,
  },
  'pdf-viewer': {
    id: 'pdf-viewer',
    name: 'PDF Viewer',
    title: 'PDF Document Viewer',
    icon: 'FileText',
    category: 'productivity',
    description: 'Interactive PDF and document viewer with zoom, rotation, pagination, and resume inspect.',
    defaultSize: { width: 840, height: 620 },
    minimumSize: { width: 400, height: 350 },
    supportedFileTypes: ['pdf'],
    availableModes: ['explorer', 'recruiter', 'developer'],
    isPinnedDefault: false,
  },
  'notes': {
    id: 'notes',
    name: 'Workstation Notes',
    title: 'Workstation Sticky Notes',
    icon: 'StickyNote',
    category: 'productivity',
    description: 'Quick scratchpad and categorized developer notes with instant autosave and AI summary integration.',
    defaultSize: { width: 720, height: 480 },
    minimumSize: { width: 360, height: 300 },
    availableModes: ['explorer', 'recruiter', 'developer'],
    isPinnedDefault: false,
  },
  'projects': {
    id: 'projects',
    name: 'Projects Showcase',
    title: 'Production Projects Showcase',
    icon: 'FolderKanban',
    category: 'portfolio',
    description: 'Explore full-stack production projects, architectural case studies, live demos, and GitHub repositories.',
    defaultSize: { width: 940, height: 620 },
    minimumSize: { width: 500, height: 400 },
    availableModes: ['explorer', 'recruiter', 'developer'],
    isPinnedDefault: true,
  },
  'experience': {
    id: 'experience',
    name: 'Work Experience',
    title: 'Professional Engineering Experience',
    icon: 'Briefcase',
    category: 'portfolio',
    description: 'Interactive career timeline covering full-stack software development roles and production achievements.',
    defaultSize: { width: 860, height: 580 },
    minimumSize: { width: 440, height: 360 },
    availableModes: ['explorer', 'recruiter', 'developer'],
    isPinnedDefault: false,
  },
  'skills': {
    id: 'skills',
    name: 'Skills & Tech Stack',
    title: 'Technical Proficiencies & Stack',
    icon: 'Cpu',
    category: 'portfolio',
    description: 'Detailed breakdown of programming languages, frontend/backend frameworks, databases, and AI tooling.',
    defaultSize: { width: 800, height: 540 },
    minimumSize: { width: 420, height: 340 },
    availableModes: ['explorer', 'recruiter', 'developer'],
    isPinnedDefault: false,
  },
  'education': {
    id: 'education',
    name: 'Education',
    title: 'Academic Credentials & Education',
    icon: 'GraduationCap',
    category: 'portfolio',
    description: 'Bachelor of Engineering in Information Technology (8.50 CGPA) and coursework highlights.',
    defaultSize: { width: 740, height: 480 },
    minimumSize: { width: 400, height: 320 },
    availableModes: ['explorer', 'recruiter'],
    isPinnedDefault: false,
  },
  'certifications': {
    id: 'certifications',
    name: 'Certifications',
    title: 'Certifications & Credentials',
    icon: 'Award',
    category: 'portfolio',
    description: 'Verified professional certifications, cloud licenses, and specialized software credentials.',
    defaultSize: { width: 780, height: 520 },
    minimumSize: { width: 400, height: 320 },
    availableModes: ['explorer', 'recruiter'],
    isPinnedDefault: false,
  },
  'resume': {
    id: 'resume',
    name: 'Developer Resume',
    title: 'Resume — Abhishek_Kuntare.pdf',
    icon: 'FileText',
    category: 'portfolio',
    description: 'Official software developer resume with PDF rendering, download capability, and career breakdown.',
    defaultSize: { width: 840, height: 640 },
    minimumSize: { width: 420, height: 360 },
    keyboardShortcut: 'Ctrl + R',
    availableModes: ['explorer', 'recruiter', 'developer'],
    isPinnedDefault: true,
  },
  'about': {
    id: 'about',
    name: 'About Abhishek',
    title: 'About Abhishek Kuntare',
    icon: 'UserCheck',
    category: 'portfolio',
    description: 'Developer biography, engineering philosophy, production impact, and personal introduction.',
    defaultSize: { width: 760, height: 520 },
    minimumSize: { width: 400, height: 340 },
    availableModes: ['explorer', 'recruiter', 'developer'],
    isPinnedDefault: false,
  },
  'contact': {
    id: 'contact',
    name: 'Contact & Inquiries',
    title: 'Get in Touch — Abhishek Kuntare',
    icon: 'Mail',
    category: 'portfolio',
    description: 'Direct communication form, calendar booking links, email, phone, and professional network handles.',
    defaultSize: { width: 720, height: 520 },
    minimumSize: { width: 380, height: 360 },
    availableModes: ['explorer', 'recruiter', 'developer'],
    isPinnedDefault: false,
  },
  'file-explorer': {
    id: 'file-explorer',
    name: 'File Explorer',
    title: 'File Explorer — Virtual Filesystem',
    icon: 'Folder',
    category: 'system',
    description: 'Navigate virtual disks (C: and D:), organize documents, upload assets, and manage directories.',
    defaultSize: { width: 860, height: 560 },
    minimumSize: { width: 460, height: 360 },
    keyboardShortcut: 'Ctrl + E',
    availableModes: ['explorer', 'developer'],
    isPinnedDefault: true,
  },
  'downloads': {
    id: 'downloads',
    name: 'Downloads',
    title: 'Downloads & Received Files',
    icon: 'Folder',
    category: 'system',
    description: 'Manage files downloaded inside Abhishek OS and browser sessions.',
    defaultSize: { width: 800, height: 500 },
    minimumSize: { width: 420, height: 320 },
    availableModes: ['explorer', 'developer'],
    isPinnedDefault: false,
  },
  'recycle-bin': {
    id: 'recycle-bin',
    name: 'Recycle Bin',
    title: 'Recycle Bin',
    icon: 'Trash2',
    category: 'system',
    description: 'View and restore deleted files or permanently empty trash.',
    defaultSize: { width: 740, height: 480 },
    minimumSize: { width: 400, height: 300 },
    availableModes: ['explorer'],
    isPinnedDefault: false,
  },
  'settings': {
    id: 'settings',
    name: 'Workstation Settings',
    title: 'Workstation Settings',
    icon: 'Settings',
    category: 'system',
    description: 'System personalization, live wallpapers, sound effects, display brightness, and performance presets.',
    defaultSize: { width: 820, height: 560 },
    minimumSize: { width: 440, height: 360 },
    availableModes: ['explorer', 'recruiter', 'developer'],
    isPinnedDefault: true,
  },
  'performance': {
    id: 'performance',
    name: 'Performance Center',
    title: 'Performance Center — Web Vitals & Runtime Telemetry',
    icon: 'Activity',
    category: 'system',
    description: 'Real measurable browser metrics (FCP, LCP, CLS, TTFB), memory usage, FPS counter, and resource latency.',
    defaultSize: { width: 820, height: 540 },
    minimumSize: { width: 440, height: 360 },
    availableModes: ['explorer', 'developer'],
    isPinnedDefault: false,
  },
  'security': {
    id: 'security',
    name: 'Security Center',
    title: 'Security Center — Audits & Sandboxing',
    icon: 'ShieldCheck',
    category: 'system',
    description: 'Audit report on sandbox boundaries, HTTPS protocol, storage isolation, safe AI tools, and zero-eval policy.',
    defaultSize: { width: 800, height: 540 },
    minimumSize: { width: 440, height: 360 },
    availableModes: ['explorer', 'developer'],
    isPinnedDefault: false,
  },
  'system-monitor': {
    id: 'system-monitor',
    name: 'Task Manager',
    title: 'Task Manager — Processes & Resources',
    icon: 'Activity',
    category: 'system',
    description: 'Inspect active OS windows, end tasks, and monitor synthetic CPU/Memory utilization.',
    defaultSize: { width: 740, height: 480 },
    minimumSize: { width: 400, height: 320 },
    keyboardShortcut: 'Ctrl + Shift + Esc',
    availableModes: ['explorer', 'developer'],
    isPinnedDefault: false,
  },
  'system-info': {
    id: 'system-info',
    name: 'System Information',
    title: 'Workstation Hardware & OS Specs',
    icon: 'HardDrive',
    category: 'system',
    description: 'Workstation hardware specifications, React 19 runtime, browser environment, and deployment details.',
    defaultSize: { width: 720, height: 480 },
    minimumSize: { width: 380, height: 300 },
    availableModes: ['explorer', 'developer'],
    isPinnedDefault: false,
  },
  'this-pc': {
    id: 'this-pc',
    name: 'This PC',
    title: 'This PC — System Storage',
    icon: 'Monitor',
    category: 'system',
    description: 'System drives (C: System, D: Portfolio Data) and directory overview.',
    defaultSize: { width: 800, height: 520 },
    minimumSize: { width: 420, height: 340 },
    availableModes: ['explorer'],
    isPinnedDefault: true,
  },
  'camera': {
    id: 'camera',
    name: 'Camera & Video Studio',
    title: 'Camera & Video Studio',
    icon: 'Camera',
    category: 'media',
    description: 'Webcam snapshot studio with color grading filters, video capture, and direct saving to /Pictures VFS.',
    defaultSize: { width: 800, height: 540 },
    minimumSize: { width: 420, height: 360 },
    permissions: ['camera', 'microphone'],
    availableModes: ['explorer'],
    isPinnedDefault: false,
  },
  'video-player': {
    id: 'video-player',
    name: 'Media Player',
    title: 'Media Video Player',
    icon: 'Video',
    category: 'media',
    description: 'Multimedia video player supporting MP4 playback, playlists, and speed controls.',
    defaultSize: { width: 800, height: 520 },
    minimumSize: { width: 420, height: 340 },
    supportedFileTypes: ['mp4', 'webm'],
    availableModes: ['explorer'],
    isPinnedDefault: false,
  },
  'gallery': {
    id: 'gallery',
    name: 'Media Gallery',
    title: 'Workstation Media Gallery',
    icon: 'Images',
    category: 'media',
    description: 'Photo and artwork showcase featuring UI designs, architecture diagrams, and camera snapshots.',
    defaultSize: { width: 840, height: 560 },
    minimumSize: { width: 440, height: 360 },
    supportedFileTypes: ['jpg', 'png', 'svg', 'webp'],
    availableModes: ['explorer'],
    isPinnedDefault: false,
  },
  'youtube': {
    id: 'youtube',
    name: 'YouTube Studio',
    title: 'YouTube Embed Studio',
    icon: 'Youtube',
    category: 'media',
    description: 'Watch developer tutorials, keynotes, and engineering demos.',
    defaultSize: { width: 860, height: 540 },
    minimumSize: { width: 440, height: 360 },
    availableModes: ['explorer'],
    isPinnedDefault: false,
  },
  'spotify': {
    id: 'spotify',
    name: 'Spotify Music',
    title: 'Spotify Music Station',
    icon: 'Music',
    category: 'media',
    description: 'Ambient background music and developer focus playlists.',
    defaultSize: { width: 820, height: 520 },
    minimumSize: { width: 420, height: 360 },
    availableModes: ['explorer'],
    isPinnedDefault: false,
  },
  'music-player': {
    id: 'music-player',
    name: 'Audio Player',
    title: 'Audio Music Player',
    icon: 'Music',
    category: 'media',
    description: 'Local audio file playback from VFS Music directory.',
    defaultSize: { width: 720, height: 460 },
    minimumSize: { width: 380, height: 300 },
    supportedFileTypes: ['mp3', 'wav', 'ogg'],
    availableModes: ['explorer'],
    isPinnedDefault: false,
  },
  'arcade': {
    id: 'arcade',
    name: 'Arcade Center',
    title: 'Abhishek Arcade — Retro Games',
    icon: 'Gamepad2',
    category: 'entertainment',
    description: 'Playable retro developer mini-games: Snake, Minesweeper, Solitaire, and high-score leaderboards.',
    defaultSize: { width: 840, height: 600 },
    minimumSize: { width: 480, height: 400 },
    availableModes: ['explorer'],
    isPinnedDefault: false,
  },
  'achievements': {
    id: 'achievements',
    name: 'Achievements',
    title: 'Portfolio Achievements & Milestones',
    icon: 'Trophy',
    category: 'portfolio',
    description: 'Track portfolio milestones, GamerScore, and unlock exploration badges.',
    defaultSize: { width: 800, height: 540 },
    minimumSize: { width: 440, height: 360 },
    availableModes: ['explorer', 'developer'],
    isPinnedDefault: false,
  },
  'widgets': {
    id: 'widgets',
    name: 'Widgets Board',
    title: 'Workstation Widgets Board',
    icon: 'Sparkles',
    category: 'system',
    description: 'Live weather radar, system stats, quick notes, and calendar overview.',
    defaultSize: { width: 780, height: 560 },
    minimumSize: { width: 420, height: 360 },
    availableModes: ['explorer'],
    isPinnedDefault: false,
  },
  'weather': {
    id: 'weather',
    name: 'Weather',
    title: 'Weather Forecast',
    icon: 'CloudSun',
    category: 'system',
    description: 'Global weather outlook and atmospheric telemetry.',
    defaultSize: { width: 720, height: 480 },
    minimumSize: { width: 380, height: 320 },
    availableModes: ['explorer'],
    isPinnedDefault: false,
  },
  'calculator': {
    id: 'calculator',
    name: 'Calculator',
    title: 'Scientific Calculator',
    icon: 'Calculator',
    category: 'productivity',
    description: 'Standard and scientific mathematical calculator with memory functions.',
    defaultSize: { width: 360, height: 480 },
    minimumSize: { width: 320, height: 420 },
    availableModes: ['explorer', 'developer'],
    isPinnedDefault: false,
  },
  'calendar': {
    id: 'calendar',
    name: 'Calendar',
    title: 'Calendar & Milestones',
    icon: 'Calendar',
    category: 'productivity',
    description: 'Schedule planner, milestones, and developer release events.',
    defaultSize: { width: 760, height: 500 },
    minimumSize: { width: 400, height: 340 },
    availableModes: ['explorer'],
    isPinnedDefault: false,
  },
  'snipping-tool': {
    id: 'snipping-tool',
    name: 'Snipping Tool',
    title: 'Snipping & Screen Capture',
    icon: 'Sparkles',
    category: 'system',
    description: 'Workstation screen capture and annotation utility.',
    defaultSize: { width: 500, height: 360 },
    minimumSize: { width: 380, height: 260 },
    availableModes: ['explorer'],
    isPinnedDefault: false,
  },
  'admin': {
    id: 'admin',
    name: 'Control Center',
    title: 'Abhishek Portfolio Control Center',
    icon: 'ShieldAlert',
    category: 'system',
    description: 'Administrative portal for real-time project management and content updates.',
    defaultSize: { width: 900, height: 600 },
    minimumSize: { width: 480, height: 380 },
    availableModes: ['developer'],
    isPinnedDefault: false,
  },
  'control-panel': {
    id: 'control-panel',
    name: 'Control Panel',
    title: 'Control Panel',
    icon: 'SlidersHorizontal',
    category: 'system',
    description: 'Central navigation for settings, security, and performance tools.',
    defaultSize: { width: 820, height: 560 },
    minimumSize: { width: 520, height: 380 },
    availableModes: ['explorer'],
    isPinnedDefault: false,
  },
  'store': {
    id: 'store',
    name: 'Abhishek Store',
    title: 'Abhishek Store',
    icon: 'Store',
    category: 'system',
    description: 'Discover and manage the built-in apps that power your Abhishek OS workstation.',
    defaultSize: { width: 1040, height: 700 },
    minimumSize: { width: 640, height: 480 },
    availableModes: ['explorer', 'developer', 'recruiter'],
    isPinnedDefault: false,
  },
};

export function getAppMetadata(appId: AppId): AppMetadata {
  return (
    APP_REGISTRY[appId] || {
      id: appId,
      name: appId,
      title: appId,
      icon: 'Monitor',
      category: 'system',
      description: '',
      defaultSize: { width: 800, height: 520 },
      minimumSize: { width: 400, height: 300 },
      availableModes: ['explorer', 'developer', 'recruiter'],
    }
  );
}

export function getAppsForMode(mode: 'explorer' | 'recruiter' | 'developer'): AppMetadata[] {
  return Object.values(APP_REGISTRY).filter(app => app.availableModes.includes(mode));
}
